exclude:
- README.md
- screenshot.png
- LICENSE
- Gemfile
- Gemfile.lock
- docs/*
- doc/*
- .gemspec

# Installed Gems
gems: [
  jekyll-sitemap,
  jekyll-mentions,
  jekyll-paginate,
  jekyll-seo-tag,
  jekyll-redirect-from,
  jekyll-feed,
  jemoji,
  jekyll-paginate-category,
  jekyll-admin
]

# Site settings
title: Java Server Faces
email: info@javaserverfaces.com
description: > # this means to ignore newlines until "baseurl:"
  JavaServer Faces - Rich Application Platform, Community Portal, Resource Center
baseurl: ''
url: 'http://dev.javaserverfaces.com'
twitter_username: ''
github_username: jsf-site

# Build settings
markdown: kramdown

paginate: 3
paginate_path: 'news/page:num'

destination: ./docs
keep_files: ['CNAME']