exclude:
- README.md
- screenshot.png
- LICENSE
- Gemfile
- Gemfile.lock
- docs/*
- doc/*
- .gemspec

# Installed Gems
gems: [
  jekyll-sitemap,
  jekyll-mentions,
  jekyll-paginate,
  jekyll-seo-tag,
  jekyll-redirect-from,
  jekyll-feed,
  jemoji,
  jekyll-paginate-category,
  jekyll-admin
]

# Site settings
title: JavaServer Faces.org
email: info@javaserverfaces.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ''
url: 'http://dev.javaserverfaces.com'
twitter_username: ''
github_username: jsf-site

# Build settings
markdown: kramdown

paginate: 3
paginate_path: 'news/page:num'

destination: ./docs
keep_files: ['CNAME']